#!/bin/sh -e

### BEGIN INIT INFO
# Provides:          EmbeddedEngine Module FanSmart
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     5
# Default-Stop:
# Short-Description: Ventillateur on/off
# Description:       Gestion du ventillateur par la temperature
### END INIT INFO

DAEMON="/usr/local/bin/embedded_engine/home_connect"
DAEMON_ARGS=""
DAEMON_NAME="home_connect"

. /lib/lsb/init-functions
ldconfig $DAEMON

mkdir -p /home/pi/logs

do_start() {
	log_daemon_msg "Starting $DAEMON_NAME [$DAEMON]"
	start-stop-daemon --background --name $DAEMON_NAME --start --quiet --exec $DAEMON
	log_end_msg $?
}

do_stop() {
	log_daemon_msg "Ending $DAEMON_NAME [$DAEMON]"
	start-stop-daemon --name $DAEMON_NAME --stop --retry 5 --quiet --name $DAEMON_NAME
	log_end_msg $?
}


case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart|reload|force-reload)
		do_start
		do_stop
		;;
	force-stop)
		d_stop
		killall -q $DAEMON_NAME || true
		sleep 2
		killall -q -9 $DAEMON_NAME || true
		;;
	status)
		status_of_proc "$DAEMON_NAME" "$DAEMON" "system-wide $DAEMON_NAME" && exit 0 || exit $?
	        ;;
	*)	echo "Usage: /etc/init.d/S99EmbeddedModule {start|stop|force-stop|status|restart|reload|force-reload}"
		touch /home/pi/NOPE
		exit 1
		;;
esac
exit 0